export CUDA_VISIBLE_DEVICES=1
export FIVEK_PATCHSET_DIR=patchsets/fivek

python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS-1D Mark II" --output-dir "./runs/extra/fivek/Canon EOS-1D Mark II"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS-1D Mark III" --output-dir "./runs/extra/fivek/Canon EOS-1D Mark III"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS-1D Mark II N" --output-dir "./runs/extra/fivek/Canon EOS-1D Mark II N"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS-1Ds Mark II" --output-dir "./runs/extra/fivek/Canon EOS-1Ds Mark II"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS 5D" --output-dir "./runs/extra/fivek/Canon EOS 5D"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS 10D" --output-dir "./runs/extra/fivek/Canon EOS 10D"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS 20D" --output-dir "./runs/extra/fivek/Canon EOS 20D"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS 30D" --output-dir "./runs/extra/fivek/Canon EOS 30D"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS 40D" --output-dir "./runs/extra/fivek/Canon EOS 40D"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS D60" --output-dir "./runs/extra/fivek/Canon EOS D60"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS DIGITAL REBEL" --output-dir "./runs/extra/fivek/Canon EOS DIGITAL REBEL"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS DIGITAL REBEL XSi" --output-dir "./runs/extra/fivek/Canon EOS DIGITAL REBEL XSi"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS DIGITAL REBEL XT" --output-dir "./runs/extra/fivek/Canon EOS DIGITAL REBEL XT"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon EOS DIGITAL REBEL XTi" --output-dir "./runs/extra/fivek/Canon EOS DIGITAL REBEL XTi"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon PowerShot G9" --output-dir "./runs/extra/fivek/Canon PowerShot G9"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon PowerShot G10" --output-dir "./runs/extra/fivek/Canon PowerShot G10"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "Canon PowerShot S70" --output-dir "./runs/extra/fivek/Canon PowerShot S70"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "D-LUX 3" --output-dir "./runs/extra/fivek/D-LUX 3"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "DCS460D         FILE VERSION 3" --output-dir "./runs/extra/fivek/DCS460D         FILE VERSION 3"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "FinePixS2Pro" --output-dir "./runs/extra/fivek/FinePixS2Pro"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "NIKON D2H" --output-dir "./runs/extra/fivek/NIKON D2H"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "NIKON D40X" --output-dir "./runs/extra/fivek/NIKON D40X"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "NIKON D70" --output-dir "./runs/extra/fivek/NIKON D70"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "NIKON D70s" --output-dir "./runs/extra/fivek/NIKON D70s"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "NIKON D80" --output-dir "./runs/extra/fivek/NIKON D80"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "NIKON D100" --output-dir "./runs/extra/fivek/NIKON D100"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "NIKON D300" --output-dir "./runs/extra/fivek/NIKON D300"
python scripts/inference.py --ckpt-path ./weights/pre_training/forward.ckpt --dataset FIVEK --camera-name "NIKON D700" --output-dir "./runs/extra/fivek/NIKON D700"
